# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basecamp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'basecamp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x61secamp.proto\x12\x08\x62\x61secamp\"\\\n\x0eMessageRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x13\n\x0breceiver_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"`\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x15\n\rerror_message\x18\x04 \x01(\t\"<\n\x13SubscriptionRequest\x12\x15\n\rsubscriber_id\x18\x01 \x01(\t\x12\x0e\n\x06topics\x18\x02 \x03(\t\"C\n\x0eUpdateResponse\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"i\n\rBatchResponse\x12\x15\n\rsuccess_count\x18\x01 \x01(\x05\x12\x15\n\rfailure_count\x18\x02 \x01(\x05\x12\x13\n\x0bmessage_ids\x18\x03 \x03(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\"D\n\x0b\x43hatMessage\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\xb5\x02\n\x0f\x42\x61secampService\x12\x44\n\x0bSendMessage\x12\x18.basecamp.MessageRequest\x1a\x19.basecamp.MessageResponse\"\x00\x12Q\n\x12SubscribeToUpdates\x12\x1d.basecamp.SubscriptionRequest\x1a\x18.basecamp.UpdateResponse\"\x00\x30\x01\x12M\n\x14SendMultipleMessages\x12\x18.basecamp.MessageRequest\x1a\x17.basecamp.BatchResponse\"\x00(\x01\x12:\n\x04\x43hat\x12\x15.basecamp.ChatMessage\x1a\x15.basecamp.ChatMessage\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basecamp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=28
  _globals['_MESSAGEREQUEST']._serialized_end=120
  _globals['_MESSAGERESPONSE']._serialized_start=122
  _globals['_MESSAGERESPONSE']._serialized_end=218
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=220
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=280
  _globals['_UPDATERESPONSE']._serialized_start=282
  _globals['_UPDATERESPONSE']._serialized_end=349
  _globals['_BATCHRESPONSE']._serialized_start=351
  _globals['_BATCHRESPONSE']._serialized_end=456
  _globals['_CHATMESSAGE']._serialized_start=458
  _globals['_CHATMESSAGE']._serialized_end=526
  _globals['_BASECAMPSERVICE']._serialized_start=529
  _globals['_BASECAMPSERVICE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
